---
# Playbook name: Installs Vagrant on Windows
- name: Install Vagrant on Windows
  hosts: win  # Targets the 'win' group of Windows hosts
  tasks:
    - name: Install Chocolatey (if not installed)
      win_shell: |
        if (-Not (Test-Path "C:\ProgramData\chocolatey")) {
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }
      args:
        executable: powershell  # Ensures the script runs in PowerShell

    - name: Install Vagrant via Chocolatey
      win_chocolatey:
        name: vagrant  # Name of the package to install
        state: present  # Ensures the package is installed

    - name: Ensure Vagrant is in PATH
      win_path:
        elements:
          - "C:\\Program Files\\HashiCorp\\Vagrant\\bin"  # Adds Vagrant's binary folder to the system PATH

    - name: Verify Vagrant Installation
      win_shell: vagrant --version  # Runs Vagrant version command to check installation
      register: vagrant_version  # Stores the command output in a variable

    - name: Show Installed Vagrant Version
      debug:
        msg: "Vagrant Installed: {{ vagrant_version.stdout }}"  # Displays the installed Vagrant version
