Vagrant.configure('2') do |config|
  (1..1).each do |i|
    config.vm.define "webserver" do |machine|
      machine.vm.box = 'generic/ubuntu2204'
      machine.vm.network "private_network", ip: '192.168.121.20'
      machine.vm.hostname = "webserver"
      
      machine.vm.provider "libvirt" do |libvirt|
        libvirt.cpus = 1
        libvirt.memory = 2048
      end

      # Paylaşılacak klasörü belirtin (commands klasörü)
      machine.vm.synced_folder "./commands", "/home/vagrant/commands", type: "9p",
        accessmode: "mapped"

      # Provisioning block to run the commands.sh script
      machine.vm.provision "shell", inline: "bash /home/vagrant/commands/commands.sh"
    end
  end
end

