Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11"

  # IP adresini belirt
  config.vm.network "private_network", ip: "172.25.208.10"

  config.vm.provider "hyperv" do |hv|
    hv.memory = 8192
    hv.cpus = 2
    hv.enable_virtualization_extensions = true
  end

  # WinRM bağlantı ayarları 
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.transport = :plaintext
  config.winrm.timeout = 600  # 10 dakikaya çıkardım
  config.winrm.retry_limit = 15  # Bağlantı sorunlarını azaltmak için deneme sayısını artırdım
  
end
