Vagrant.configure('2') do |config|
  (1..1).each do |i|
    config.vm.define "ansible" do |machine|
      machine.vm.box = "generic/ubuntu2204"
      machine.vm.hostname = "ansible"
      
      # Host-Only Adapter Kullanımı - VMware için
      machine.vm.network "private_network", ip: "192.168.168.20", auto_config: true
      
      # Synced Folder Ayarları (VMware uyumlu)
      # VMware sağlayıcısı için 'type' belirtmeye gerek yoktur
      machine.vm.synced_folder "./ansible", "/home/vagrant/ansible"

      # VMware Desktop Sağlayıcısı Ayarları
      machine.vm.provider "vmware_desktop" do |vb|
        vb.gui = true  # GUI modunda başlatmak istersen bunu true yap
        vb.cpus = 1
        vb.memory = 2048
      end

      # Provisioning Komutları
      machine.vm.provision "shell", inline: <<-SHELL
        if [ -f /home/vagrant/ansible/kurulumlar.sh ]; then
          chmod +x /home/vagrant/ansible/kurulumlar.sh
          sudo bash /home/vagrant/ansible/kurulumlar.sh
        else
          echo "kurulumlar.sh bulunamadı. Lütfen doğru dizinde olduğundan emin olun."
        fi
      SHELL
    end
  end
end
