---
- name: Install QEMU and enable virtualization on Windows
  hosts: win
  tasks:
    - name: Download QEMU installer
      win_get_url:
        url: "https://qemu.weilnetz.de/w64/qemu-w64-setup-20250422.exe"
        dest: "C:\\Users\\{{ ansible_user | quote }}\\Downloads\\qemu_installer.exe"

    - name: Install QEMU
      win_command: "C:\\Users\\{{ ansible_user | quote }}\\Downloads\\qemu_installer.exe /S"
      args:
        creates: "C:\\Program Files\\qemu"

    - name: Add QEMU to PATH
      win_path:
        elements:
          - "C:\\Program Files\\qemu"

    - name: Enable Hyper-V feature
      win_shell: |
        Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All -NoRestart -All

    - name: Enable Hypervisor Platform
      win_shell: |
        Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -NoRestart -All

    - name: Enable Virtual Machine Platform
      win_shell: |
        Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform -NoRestart -All
