---
- name: Prepare PowerShell + BAT scripts to launch QEMU VMs via GUI
  hosts: win
  gather_facts: no
  tasks:

    - name: Read QCOW2 file names from Ansible control machine
      delegate_to: localhost
      find:
        paths: "/home/vagrant/shared_images"
        patterns: "*.qcow2"
        recurse: no
      register: local_qcow_files

    - name: Extract file names
      set_fact:
        qcow2_filenames: "{{ local_qcow_files.files | map(attribute='path') | map('basename') | list }}"

    - name: Create PowerShell script folder
      win_file:
        path: "C:\\vagrant_vm_boot"
        state: directory

    - name: Create PowerShell scripts for each QCOW2 file (advanced QEMU command)
      win_copy:
        content: |
          qemu-system-x86_64 `
            -accel whpx `
            -m 4096 `
            -drive file="C:\Users\vagrant\shared_f\{{ item }}",format=qcow2,if=virtio `
            -netdev user,id=net0 `
            -device virtio-net,netdev=net0 `
            -boot c
        dest: "C:\\vagrant_vm_boot\\start_vm_{{ item | replace('.qcow2', '') }}.ps1"
      loop: "{{ qcow2_filenames }}"
      when: qcow2_filenames | length > 0

    - name: Create .bat file in Startup folder for each PowerShell script
      win_copy:
        content: |
          powershell.exe -ExecutionPolicy Bypass -NoExit -WindowStyle Normal -File "C:\vagrant_vm_boot\start_vm_{{ item | replace('.qcow2', '') }}.ps1"
        dest: "C:\\Users\\vagrant\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\start_vm_{{ item | replace('.qcow2', '') }}.bat"
      loop: "{{ qcow2_filenames }}"
      when: qcow2_filenames | length > 0

    - name: Reboot the machine
      win_reboot:
        reboot_timeout: 600
      when: qcow2_filenames | length > 0
