Vagrant.configure('2') do |config|
  config.vm.define "windows11" do |machine|
    machine.vm.box = "gusztavvargadr/windows-11"
    machine.vm.hostname = "windows11"

    # İlk ağ kartı - NAT (VMware'in varsayılan ayarı)
    machine.vm.network "public_network", bridge: "VMnet2"

    # İkinci ağ kartı - Host-Only (VMnet2 üzerinden)
    machine.vm.network "private_network", ip: "192.168.168.15", auto_config: false

    # VMware Workstation Pro Sağlayıcısı Ayarları
    machine.vm.provider "vmware_desktop" do |vb|
      vb.gui = true                
      vb.cpus = 4                  
      vb.memory = 8192             
      
      # İlk Ethernet Kartı (NAT için)
      vb.vmx["ethernet0.pcislotnumber"] = "33"
      vb.vmx["ethernet0.connectiontype"] = "nat"     
      vb.vmx["ethernet0.virtualdev"] = "e1000"
      vb.vmx["ethernet0.addressType"] = "generated"
      
      # İkinci Ethernet Kartı (Host-Only - VMnet2)
      vb.vmx["ethernet1.pcislotnumber"] = "34"
      vb.vmx["ethernet1.connectiontype"] = "hostonly"  # VMnet2 (Host-Only Network)
      vb.vmx["ethernet1.virtualdev"] = "e1000"
      vb.vmx["ethernet1.addressType"] = "generated"
      vb.vmx["ethernet1.vnet"] = "VMnet2"              # Özel olarak VMnet2'yi kullan
    end

    # Windows VM için iletişim yöntemi - WinRM
    machine.vm.communicator = "winrm"

    # Windows Statik IP Ayarları
    machine.vm.provision "shell", privileged: true, inline: <<-SHELL
      # İlk Kart (NAT) için IP Ayarları
      netsh interface ip set address "Ethernet" static 192.168.168.11 255.255.255.0
      netsh interface ip set dns "Ethernet" static 192.168.168.1
      netsh interface ip add dns "Ethernet" 8.8.8.8 index=2
      
      # İkinci Kart (Host-Only - VMnet2) için IP Ayarları
      netsh interface ip set address "Ethernet 2" static 192.168.168.15 255.255.255.0
      netsh interface ip set dns "Ethernet 2" static 192.168.168.1
    SHELL
  end
end
