
Vagrant.configure("2") do |config|
  config.vm.box = "generic-x64/ubuntu2204"
  config.vm.provision "shell", path: "scripts/req.sh"
  config.vm.network "private_network", ip: "192.168.121.20"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "/home/reqwert/Desktop/vagrant-vmware/win11/images", "/home/vagrant/shared_images", type: "rsync"

end
